### ISSUE TITLE
Programming error in compass_svc.py

### ISSUE THREAD

**Issue by tonygoda** [mitre/compass#30]
The compass isn't working with Caldera MITRE to create an adversary profile from COMPASS GUI. I have uploaded the json file, which was created from the ATT&CK matrix to the COMPASS GUI by clicking Upload Adversary Layer button.

Although the adversary.yml file is created in the caldera/data directory I saw an extra field in the file, key: value pair being **i: UUID**. Then I checked the create_adversary_from_layer function in the compass_svc.py file, where I found that instead of the parameter being **id** it was **i** (check it in the 2nd try block, **adversary_data = dict(i=str(uuid.uuid4()),**). 

I have changed the variable to id and the COMPASS module worked fine. Please check the issue and update the code.

**Comment by wbooth** [comment]
Thanks Tony, if you already have the fix please submit a PR

**Comment by tonygoda** [comment]
I wouldn't say it is a fix because it is a programming error. In the compass_svc.py please change the code **adversary_data = dict(i=str(uuid.uuid4()),).** to **adversary_data = dict(id=str(uuid.uuid4()),).**, which is basically replacing the variable i with id.

**Comment by wbooth** [comment]
Thank you!
