### ISSUE TITLE
Generate layer 'check' then use it to generate adversary result in 3x times abilities.

### ISSUE THREAD

**Issue by alshaboti** [mitre/compass#32]
I used a compass to generate layer for `check` adversary profile (which has 12 abilities), I downloaded the `layer.json` file. Then I feed it (`layer.json`) to generate adversary. The generated adversary has  42 abilities, while the layer.json file was generated for the `check` adversary which has 12 abilities. 

Setup: `Caldera version 2.8.0-909597268607e7cbca77bd22c462fb22` in `Docker  version 18.09.7` in `Ubuntu 16.04`.

[layer.txt](https://github.com/mitre/compass/files/5274846/layer.txt)

**Comment by wbooth** [comment]
Compass will pull all abilities for the specified techniques into the adversary

**Comment by alshaboti** [comment]
I didn't quite get it, if I download a layer then upload it, I expect to get same adversary profile with same capabilities. 

I tried with the `check` profile, to download it upload it multiple times, and each time the profile abilities increase from 12 to 42 to 70 and so on.

**Comment by wbooth** [comment]
The layer file only specifies tactics and techniques and does not keep a record of individual abilities. So when you upload a layer file that specifies a technique compass will include all abilities that relate to that technique in the adversary.

**Comment by alshaboti** [comment]
@wbooth  thanks for the clarification.
